#!/usr/bin/python

# reads json text from stdin and writes prettyfied json to stdout

import sys
import json

lines = sys.stdin.readlines()
data = "".join(lines)
tree = json.loads(data)
pretty = json.dumps(tree, indent=4)
sys.stdout.write(pretty)